### ISSUE TITLE
Fix for ASCII GPG Keys Not Being Recognized by APT in s1-agent-install-repo.sh Script

### ISSUE THREAD

**Issue by maorteg** [s1community/install-tools#18]
https://github.com/s1community/install-tools/blob/c9c05f6176e1c4bf915dc1833c4cbc4b02215432/linux/s1-agent-install-repo.sh#L173

Hello @s1-howie

The curl option -s disables standard output, resulting in no data in the pipe and empty files are created in _/etc/apt/trusted.gpg.d/_.  Also, the [published key](https://deb.sentinelone.net/v1/gpg/package-key.gpg) is in ASCII while APT expects binary format with this extension.

The curl option -O cannot be used, it redirects the output to a file in the current dir. Also, both apt-key.gpg and repo-signing-key.gpg are ASCII and will be ignored by apt unless converted to binary:

```
curl -sL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/sentinelone-apt-key.gpg 
curl -sL https://us-apt.pkg.dev/doc/repo-signing-key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/sentinelone-repo-signing-key.gpg
```

**Comment by s1-tkaspar** [comment]
@maorteg @s1-howie 

Updates to the `curl` flags and `gpg --dearmor` command have been committed to the main branch.

I also reorganized the user prompts when arguments or `s1.config` is not provided to follow the same order as arguments.

I'll keep this issue open through the end of the week for feedback.

**Comment by s1-tkaspar** [comment]
https://github.com/s1community/install-tools/commit/fdd61526ad341203a3750a255704fe9cb22fd2d4

**Comment by maorteg** [comment]
New commit with dedicated branch: [c8ee69c](https://github.com/s1community/install-tools/commit/c8ee69ca29f7a12382eca7323293bded965d3cf4).

**Comment by s1-tkaspar** [comment]
Thank you @maorteg
Changes have been merged to main, closing issue.
